#MPRG春の勉強2021 第10回：問題解決の方法 (課題)


"問題解決の方法"と関係のない話になりますが，Pythonにおける全てのエラー(\*Error)はクラスとして定義されており，BaseExceptionからサブクラス(継承)を重ねて派生しています．例外(Exception)にSyntaxErrorが属していたり，BaseExceptionに警告(\*Warning)が属していたりします．気になる人は[組み込み例外の公式ドキュメント](https://docs.python.org/ja/3/library/exceptions.html)を一度読んでみると良いでしょう．

---
## SyntaxError

In [ ]:
# SyntaxError
# 文字列を出力したい

# 欲しい出力：
# Hello world

print("Hello world")

Hello world


In [ ]:
# IndentationError：SyntaxErrorのサブクラス
# 無駄にif文を使って文字列を出力したい

# 欲しい出力：
# Hello
# world

if True:
  print("Hello")
if True:
  print("world")

Hello
world


---
## 例外

In [ ]:
# AttributeError
# mathモジュールにあるコサイン関数を使ってコサインゼロの値を出力したい

# 欲しい出力：
# cos(0) = 1.0

import math

print("cos(0) =", math.cos(0))

cos(0) = 1.0


In [ ]:
# ImportError
# mathモジュールからインポートしたサイン関数を使ってサインゼロの値を出力したい

# 欲しい出力：
# sin(0) = 0.0

from math import sin

print("sin(0) =", sin(0))

sin(0) = 0.0


In [ ]:
# TypeError
# 文字列(Hello world)を3回(numの数だけ)出力したい

# 欲しい出力：
# Hello world
# Hello world
# Hello world

num = 3.0
for _ in range(int (num)):
  print("Hello world")

Hello world
Hello world
Hello world


In [ ]:
# ValueError
# 行列の足し算をしたい

# 欲しい出力：
# arr3:
#  [[ 0  2  4]
#  [ 6  8 10]]
# arr3.size:
#  6

import numpy as np

arr1 = np.arange(6).reshape((2, 3))
arr2 = np.arange(6).reshape((2, 3))
arr3 = arr1 + arr2

print("arr3:\n", arr3)
print("arr3.size:\n", arr3.size)

arr3:
 [[ 0  2  4]
 [ 6  8 10]]
arr3.size:
 6


In [ ]:
# RuntimeError
# ネットワーク定義と画像の入出力をしたい

# 欲しい出力：
# output.shape:
#  torch.Size([1, 10])
# model_arch:
#  NN(
#    [ネットワーク構造は指定しません]
#  )

import torch
from torch import nn

num_classes = 10 # クラス数は10。変えないように。
input = torch.randn(1, 3, 32, 32) # 入力画像としてサイズ32x32のRGB画像１枚を想定し，そのサイズの乱数を生成。変えないように。
nchannel = 64 # 全結合層の入力サイズ。変えないように。

class NN(nn.Module):
  def __init__(self, out_units, nchannel):
    super(NN, self).__init__()
    self.activation = nn.ReLU()
    self.nchannel = nchannel

    self.conv1 = nn.Conv2d(3, 128, 3, padding=1)
    self.mp1 = nn.MaxPool2d(2, stride=2, padding=0)
    self.conv2 = nn.Conv2d(128, 4, 3, padding=1)
    self.mp2 = nn.MaxPool2d(4, stride=4, padding=0)
    self.l1 = nn.Linear(self.nchannel, 32)
    self.l2 = nn.Linear(32, out_units)
    self.out = nn.Softmax(dim=1)

  def forward(self, x):
    x = self.conv1(x)
    x = self.activation(x)
    x = self.mp1(x)

    x = self.conv2(x)
    x = self.activation(x)
    x = self.mp2(x)

    x = x.view(-1, self.nchannel)
    x = self.l1(x)
    x = self.l2(x)
    return self.out(x)

model = NN(num_classes, nchannel)
output = model(input)

print("output.shape:\n", output.shape)
print("model_arch:\n", model)

output.shape:
 torch.Size([1, 10])
model_arch:
 NN(
  (activation): ReLU()
  (conv1): Conv2d(3, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  (mp1): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
  (conv2): Conv2d(128, 4, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  (mp2): MaxPool2d(kernel_size=4, stride=4, padding=0, dilation=1, ceil_mode=False)
  (l1): Linear(in_features=64, out_features=32, bias=True)
  (l2): Linear(in_features=32, out_features=10, bias=True)
  (out): Softmax(dim=1)
)
